<?php
/*---------------------------------------------------+
| HoloCMS - Website and Content Management System
+----------------------------------------------------+
| Copyright &copy; 2008 Meth0d
+----------------------------------------------------+
| HoloCMS is provided "as is" and comes without
| warrenty of any kind.
+---------------------------------------------------*/

// Disclaimer / Terms of Service
$locale['terms_of_service_title'] = "Condiciones de uso";
$locale['terms_of_service'] = "Bienvenido al sitio web de un Habbo retro.

Te agradecemos que leas atentamente el conjunto de disposiciones siguientes que rigen el uso del sitio (en adelante denominadas las &quot;Condiciones de uso&quot;).

Si eres menor de 18 a&ntilde;os, debes pedir a tus padres o tutores que te expliquen todos los t&eacute;rminos o expresiones utilizados a continuaci&oacute;n que no entiendas y validar con ellos tu decisi&oacute;n de aceptar el conjunto de las Condiciones de uso.

1. Uso del Sitio Habbo Hotel
1.1 Los propietarios de Habbo Hotel, es decir, la empresa Sulake France, identificada en el RCS de Nanterre con el n&uacute;mero 478 259 211, (en adelante tambi&eacute;n denominada &quot;Sulake France&quot; o &quot;nosotros&quot;), y su empresa matriz o sus filiales (en adelante conjuntamente denominadas el &quot;Grupo Sulake&quot;) te autorizan a acceder y usar el sitio &quot;Habbo Hotel&quot; accesible en www.habbo.fr, sus extensiones y cualquier otro sitio que pudiera sustituirlo (en adelante denominado el/nuestro &quot;Sitio&quot;) con la condici&oacute;n de respetar el conjunto de las Condiciones de uso y la Carta de protecci&oacute;n de datos personales. Podemos modificar las Condiciones de uso en cualquier momento para adaptarlas a la evoluci&oacute;n del Sitio. Ser&aacute;s informado de estas modificaciones en la p&aacute;gina de inicio del Sitio.
1.2 Salvo indicaci&oacute;n contraria, las Condiciones de uso se aplicar&aacute;n acumulativamente a todas las condiciones particulares (en adelante denominadas las &quot;Condiciones Particulares&quot;) aplicables al uso de ciertos productos o servicios ofrecidos por Sulake France o por un tercero y accesibles a trav&eacute;s del Sitio. Estas Condiciones Particulares podr&aacute;n dictarse puntualmente en relaci&oacute;n con tales productos o servicios. En caso de contradicci&oacute;n entre las Condiciones de uso y las Condiciones Particulares, estas &uacute;ltimas prevalecer&aacute;n en la medida de la contradicci&oacute;n de los t&eacute;rminos.
1.3 Para usar las funcionalidades ofrecidas por el Sitio (estas funcionalidades se denominan en adelante el &quot;Servicio&quot;), debes registrarte como usuario autorizado. Para permitir tu registro, debes proporcionarnos la informaci&oacute;n que se te solicite de manera sincera, completa y exacta y mantenerla actualizada regularmente. Deber&aacute;s informarnos de cualquier modificaci&oacute;n de dicha informaci&oacute;n por correo electr&oacute;nico. En caso de comunicaci&oacute;n de informaci&oacute;n err&oacute;nea, nos reservamos el derecho de proceder a la eliminaci&oacute;n de tu Cuenta tras requerirte que rectifiques dicha informaci&oacute;n, notificado por correo electr&oacute;nico, si no se subsana en un plazo de cuarenta y ocho (48) horas.
1.4 Eres responsable de mantener la confidencialidad y el uso correcto de tu nombre de usuario y contrase&ntilde;a. Asumes su custodia y los riesgos de p&eacute;rdida. Por este motivo, debes tomar todas las medidas necesarias para garantizar su confidencialidad, seguridad y uso correcto, as&iacute; como para evitar que sean revelados a terceros no autorizados. Eres el &uacute;nico responsable del uso por parte de cualquier otra persona de tu nombre de usuario y contrase&ntilde;a, y en particular de todas las operaciones realizadas a trav&eacute;s de la cuenta que has creado para usar el Sitio. Debes informarnos inmediatamente de cualquier uso no autorizado de tu cuenta o contrase&ntilde;a, as&iacute; como de cualquier situaci&oacute;n de la que tengas conocimiento y que pudiera dar lugar a dicho uso.
1.5 En caso de p&eacute;rdida u olvido de tu nombre de usuario o contrase&ntilde;a, debes informarnos y seguir las normas de control de seguridad que podamos establecer. Podemos suspender tu nombre de usuario y contrase&ntilde;a cuando consideremos que las normas de seguridad de todo o parte del Sitio no han sido o corren el riesgo de no ser respetadas. Podemos pedirte, de forma discrecional, que cambies el nombre de usuario y/o la contrase&ntilde;a que usas para conectarte al Sitio.
1.6 Te comprometes a no usar un nombre de usuario o contrase&ntilde;a perteneciente a otro usuario, independientemente de la autorizaci&oacute;n o no de este &uacute;ltimo.
Te comprometes a no elegir un nombre de usuario que vulnere los derechos de terceros y en particular el derecho al nombre, el derecho de marcas o que sea contrario al orden p&uacute;blico.

1.7 Nos reservamos el derecho de aprobar o rechazar cualquier nombre de usuario o contrase&ntilde;a que hayas elegido. Nos reservamos tambi&eacute;n todos los derechos, t&iacute;tulos e intereses relativos a tu nombre de usuario y contrase&ntilde;a.
1.8 Sin perjuicio de lo dispuesto en nuestra Carta de protecci&oacute;n de datos personales, nos reservamos el derecho de transferir las cuentas de usuario a cualquier empresa del Grupo Sulake.
1.9 El uso del Sitio no incluye el suministro de un ordenador ni de cualquier otro material, equipo o servicio. Para usar el Sitio, debes disponer de tus propios medios de telecomunicaciones y de acceso a Internet adecuados. En ning&uacute;n caso podremos ser responsables de los posibles gastos derivados del uso de dichos medios, tales como los gastos de conexi&oacute;n facturados por un operador de telecomunicaciones o por tu proveedor de acceso a Internet.
1.10 La propiedad del conjunto de contenidos del Sitio, incluidos sin limitaci&oacute;n todo texto, dato, sonido, im&aacute;genes, visuales, gr&aacute;ficos, fotos, disposici&oacute;n del sitio, software y cualquier otro contenido del Sitio (en adelante el &quot;Contenido&quot;), as&iacute; como la selecci&oacute;n, organizaci&oacute;n, funcionalidad, ejecuci&oacute;n y disposici&oacute;n del Contenido o de parte del Contenido es, salvo indicaci&oacute;n contraria, de titularidad exclusiva de Sulake France, su empresa matriz o sus filiales. La marca, el nombre comercial, los logotipos, los dise&ntilde;os y otros signos distintivos o caracteres de Sulake France o del Grupo Sulake, incluidos sin car&aacute;cter limitativo Habbo y Habbo Hotel, est&aacute;n protegidos por el derecho de propiedad intelectual y no pueden ser utilizados sin la autorizaci&oacute;n previa por escrito de Sulake France o del Grupo Sulake. Advertencias o restricciones adicionales que aparezcan puntualmente en ciertos elementos del Contenido pueden a&ntilde;adirse a las presentes disposiciones.
1.11 Los Programas inform&aacute;ticos para los que se te concede una licencia de uso (sin ning&uacute;n derecho de sublicencia) solo podr&aacute;n usarse en el marco del Contenido del Sitio. Solo puedes registrarte como usuario en tanto que persona f&iacute;sica. El Sitio est&aacute; exclusivamente reservado para un uso personal y no comercial. Aceptas usar el Sitio de conformidad con la normativa aplicable y con todas las normas y C&oacute;digo de conducta dictados por Sulake France para el uso del Sitio. Cualquier uso del Sitio o del Contenido con otros fines est&aacute; estrictamente prohibido y puede (i) obligarnos a ejercer nuestro derecho de rescisi&oacute;n y cierre de tu cuenta de conformidad con las presentes Condiciones de uso y/o (ii) generar tu responsabilidad civil o penal.
1.12 No debes modificar, copiar, distribuir, transmitir, difundir, mostrar, reproducir, publicar, conceder una licencia, crear obras derivadas, crear enlaces de hipertexto, reproducir, transferir o ceder ninguna de las informaciones, del Contenido y de los servicios accesibles desde el Sitio. El conjunto de los derechos de propiedad intelectual de Sulake France, o del Grupo Sulake, o de los derechos de propiedad intelectual de los proveedores y socios de Sulake est&aacute;n protegidos como tales. Si deseas m&aacute;s informaci&oacute;n sobre lo que est&aacute; permitido usar o reproducir, o sobre la posibilidad de crear un enlace de hipertexto hacia el sitio o hacia el Contenido, te rogamos que nos lo comuniques y solicites una autorizaci&oacute;n por correo electr&oacute;nico.
1.13 No debes intentar acceder a nuestros sistemas de informaci&oacute;n o a nuestras bases de datos sin autorizaci&oacute;n.
1.14 Te comprometes a usar Habbo Hotel &uacute;nicamente a trav&eacute;s del Sitio, y no a trav&eacute;s de un sitio espejo u otro medio. Te comprometes tambi&eacute;n a no crear ni proporcionar otros medios que permitan el uso de Habbo Hotel por otras personas, por ejemplo emuladores de servidores. No est&aacute;s autorizado a realizar operaciones de ingenier&iacute;a inversa, descompilar o desensamblar los Programas inform&aacute;ticos, incluidos todos los protocolos de comunicaciones utilizados por los Programas inform&aacute;ticos o el Sitio.

2. Uso del Servicio
2.1 El Servicio comprende un servicio de mensajer&iacute;a instant&aacute;nea, as&iacute; como foros de debate en los que los usuarios pueden enviar los mensajes que deseen publicar. Te comprometes a usar estos servicios exclusivamente con el fin de publicar, enviar y recibir mensajes y contenidos adecuados, conformes con los requisitos del sitio y de las presentes condiciones de uso. Eres el &uacute;nico responsable de la informaci&oacute;n, resultados de encuestas, fotograf&iacute;as, mensajes u otros contenidos que env&iacute;es o introduzcas en el sitio (&#171; el Contenido de los usuarios &#187;) y de las consecuencias derivadas de la introducci&oacute;n de dicho contenido en el Sitio. Cuando uses el servicio, te comprometes en particular a no:
2.1.1 Usar el Servicio con fines de encuesta, concurso, ventas piramidales u otras operaciones similares, o para el env&iacute;o de cadenas de correo, correos electr&oacute;nicos, spam o cualquier publicidad o elemento promocional no solicitado, ya sea con fines comerciales o no;
2.1.2 Abusar, acosar, amenazar, hacer declaraciones difamatorias, obscenas, racistas o que vulneren los derechos de los dem&aacute;s (en particular los derechos relativos al respeto de la vida privada y la publicidad);
2.1.3 Publicar, mostrar, cargar, distribuir o difundir cualquier informaci&oacute;n que a) sea il&iacute;cita o contraria a las disposiciones legales o reglamentarias aplicables o que incite a actividades de esa naturaleza; b) tenga car&aacute;cter ped&oacute;filo, pornogr&aacute;fico, expl&iacute;citamente sexual, violento u obsceno; c) requiera la comunicaci&oacute;n de datos de car&aacute;cter personal de una persona menor de quince (15) a&ntilde;os; d) tenga car&aacute;cter racista u odioso o que incite al racismo o al odio hacia otras personas o un grupo de personas; f) vulnere los derechos de propiedad intelectual de cualquier persona, incluidos los derechos de autor o los derechos de propiedad industrial; d) sea difamatoria; h) constituya una afirmaci&oacute;n falsa acerca de una persona o sus bienes o su actividad profesional realizada con malicia y susceptible de causar un perjuicio econ&oacute;mico a dicha persona; i) tenga car&aacute;cter enga&ntilde;oso o fraudulento; j) constituya una vulneraci&oacute;n de una obligaci&oacute;n de confidencialidad o una intrusi&oacute;n en el derecho a la vida privada de una persona; k) pueda llevarnos a la vulneraci&oacute;n o implicarnos en la vulneraci&oacute;n de una disposici&oacute;n legal o reglamentaria, de un c&oacute;digo o de un instrumento que rija nuestra conducta; l) pueda comprometer nuestra responsabilidad frente a cualquier persona; m) de otro modo vulnere los derechos de cualquier persona.
2.1.4 Cargar al Sitio archivos que contengan programas inform&aacute;ticos u otro elemento protegido por derechos de propiedad intelectual o derechos relativos a la vida privada o la publicidad, a menos que dispongas de los derechos correspondientes o de las autorizaciones necesarias para su explotaci&oacute;n;
2.1.5 Cargar al Sitio archivos que contengan virus, troyanos, gusanos, bombas l&oacute;gicas, archivos corruptos u otro programa inform&aacute;tico o c&oacute;digo perjudicial para los ordenadores o para los bienes ajenos;
2.1.6 Hacer publicidad o incitar a personas a comprar o vender bienes y servicios con fines comerciales;
2.1.7 Descargar cualquier archivo enviado por otro usuario cuando sepas, o puedas razonablemente dudar, que dicho archivo no puede ponerse libremente a disposici&oacute;n de terceros de ese modo;
2.1.8 Falsificar o eliminar cualquier indicaci&oacute;n que identifique a un autor, cualquier menci&oacute;n legal, cualquier t&iacute;tulo de propiedad o marcado que designe el origen de un programa inform&aacute;tico o de cualquier otro elemento contenido en un archivo cargado al Sitio;
2.1.9 Restringir o impedir el uso del Servicio por cualquier otro usuario;
2.1.10 Infringir las normas de buena conducta, o cualquier norma dictada en el Sitio para cualquier servicio o evento particular;
2.1.11 Recopilar/recolectar datos personales de otras personas, incluidas direcciones de correo electr&oacute;nico o seud&oacute;nimos, con el fin de enviar spam o correos no deseados, o de transmitir informaci&oacute;n personal relativa a otras personas;
2.1.12 Vulnerar cualquier ley o reglamento en vigor, o cualquier derecho de propiedad intelectual perteneciente a un tercero;
2.1.13 Intentar inducir a error a otros usuarios creando una identidad falsa o usurpando el nombre de otro;
2.1.14 Manipular encabezados u otros identificadores de manera que se oculte el origen de cualquier elemento transmitido a trav&eacute;s del Servicio;
2.1.15 Usar, descargar desde el Sitio o de cualquier otro modo reproducir o proporcionar a cualquier persona (de forma gratuita o a t&iacute;tulo oneroso) cualquier directorio de usuarios del Sitio o cualquier otra informaci&oacute;n relativa a usuarios o al uso del Sitio.
2.1.16 Negarse a seguir las instrucciones de cualquier representante de Sulake France o del Grupo Sulake.
2.1.17 Si detectas la presencia en el Sitio de Contenidos manifiestamente il&iacute;citos como los cuya publicaci&oacute;n est&aacute; prohibida por el art&iacute;culo 2.1.3, puedes comunic&aacute;rnoslo envi&aacute;ndonos un correo electr&oacute;nico.
2.2 Sin perjuicio de las disposiciones legales imperativas aplicables, no nos comprometemos a supervisar los contenidos, mensajes y dem&aacute;s informaci&oacute;n que los usuarios ponen a disposici&oacute;n en el Sitio. Nos reservamos no obstante el derecho, sin que ello constituya una obligaci&oacute;n, de revisar ciertos elementos publicados en l&iacute;nea, especialmente en las p&aacute;ginas de inicio o el foro de debate, y de retirar, a nuestra sola discreci&oacute;n, cualquier elemento disponible a trav&eacute;s del Servicio.
2.3 Nos reservamos el derecho discrecional de divulgar en cualquier momento cualquier informaci&oacute;n para poder respetar la normativa en vigor o la solicitud de una autoridad competente, y de modificar, negarnos a publicar o retirar cualquier informaci&oacute;n u otro elemento disponible en el Sitio.
2.4 No avalamos los contenidos, mensajes e informaci&oacute;n publicados en l&iacute;nea por los usuarios y, por este motivo, no podemos ser responsables de las consecuencias de tu uso del Servicio, y en particular de tu participaci&oacute;n o la de cualquier otro usuario en las p&aacute;ginas de inicio, los foros de debate, la mensajer&iacute;a instant&aacute;nea u otro servicio interactivo.
2.5 Los elementos cargados en las p&aacute;ginas de inicio, los foros de debate, la mensajer&iacute;a instant&aacute;nea u otro servicio pueden estar limitados en cuanto a su uso, reproducci&oacute;n y/o difusi&oacute;n. En el caso de que descargues estos elementos, debes respetar todas las limitaciones aplicables.
2.6 Conservas el conjunto de los derechos, t&iacute;tulos e intereses que posees sobre los contenidos que publicas en el Sitio. No obstante, al publicar contenidos en el Sitio, nos concedes a nosotros, as&iacute; como a las empresas vinculadas a nosotros, a nuestros subcontratistas y a nuestros socios, una licencia a t&iacute;tulo no exclusivo, v&aacute;lida durante todo el tiempo de tu uso del Sitio (as&iacute; como el derecho de sublicenciar todo o parte de los derechos siguientes) para usar, editar, modificar, reproducir, publicar y distribuir el contenido que has publicado en el Sitio en relaci&oacute;n con este y con fines comerciales razonables (incluidos la publicidad y el marketing). Concedes tambi&eacute;n a los otros usuarios del Sitio una licencia no exclusiva para acceder a los contenidos que publicas en el Sitio, y para reproducir y exponer los contenidos que publicas en el Sitio a trav&eacute;s del Sitio. Nos garantizas tambi&eacute;n frente a las perturbaciones de hecho y de derecho causadas por terceros que se pretendan los verdaderos propietarios de los derechos sobre los contenidos que publicas.
2.7 Nos reservamos el derecho de eliminar las cuentas inactivas desde hace m&aacute;s de seis meses que (i) solo hayan sido utilizadas una vez para su apertura, (ii) no contengan Cr&eacute;ditos Habbo y (iii) no contengan amigos, siendo estos criterios acumulativos.

3. Licencias de programas inform&aacute;ticos
3.1 Ponemos a tu disposici&oacute;n ciertos programas inform&aacute;ticos (los &quot;Programas&quot;) que est&aacute;s autorizado a descargar en el sitio para mejorar tu uso de este. La descarga o la obtenci&oacute;n por cualquier otro medio de cualquier elemento accesible en el marco del uso del sitio se realiza bajo tu propia responsabilidad y, a este respecto, eres el &uacute;nico responsable de todos los da&ntilde;os causados a tu sistema inform&aacute;tico y de cualquier p&eacute;rdida de datos que puedas sufrir. Los programas inform&aacute;ticos contienen informaci&oacute;n confidencial y protegida por el derecho de propiedad intelectual. El uso de los programas inform&aacute;ticos debe realizarse de conformidad con los contratos de licencia de uso que acompa&ntilde;an o est&aacute;n integrados en los programas inform&aacute;ticos (el &quot;Contrato de licencia&quot;). Estos contratos tambi&eacute;n identifican al propietario de los programas inform&aacute;ticos (el &quot;Propietario&quot;).
3.2 Debes respetar los derechos de los Propietarios de los programas inform&aacute;ticos y, en particular, no puedes realizar copias, reproducciones, transferencias, modificaciones ni crear obras derivadas de los programas inform&aacute;ticos, por ejemplo en otro servidor o cualquier otro lugar con vistas a reproducciones ulteriores, redistribuci&oacute;n, ventas, pr&eacute;stamos, alquiler alguno, salvo que est&eacute; expresamente permitido por el Contrato de licencia aplicable.
3.3 No ofrecemos ninguna garant&iacute;a relativa a los Programas inform&aacute;ticos. Las &uacute;nicas garant&iacute;as de las que dispones respecto a los Programas inform&aacute;ticos son las ofrecidas por el Propietario en el marco del Contrato de licencia aplicable.

4. Servicios de pago
4.1 Ofrecemos servicios mejorados (los &quot;Servicios Mejorados&quot;) en el Sitio a cambio de un precio. Estos Servicios Mejorados consisten en particular en servicios de descarga de iconos y tonos de llamada para tel&eacute;fono m&oacute;vil, la participaci&oacute;n en ciertos juegos y actividades, la suscripci&oacute;n a boletines informativos, la adopci&oacute;n de animales virtuales o el suministro de muebles virtuales para decorar una sala de recepci&oacute;n dentro de Habbo Hotel.
4.2 Todos los productos disponibles en el Cat&aacute;logo de Habbo Hotel se conservan en nuestros servidores, y el acceso a estos productos est&aacute; sujeto a las presentes Condiciones de uso. Estos productos no pueden en ning&uacute;n caso descargarse en tu ordenador.
4.3 Podemos, a nuestra conveniencia, retirar o a&ntilde;adir nuevos Servicios Mejorados. Estos Servicios Mejorados ser&aacute;n siempre de pago.
4.4 Determinamos las modalidades de pago de los Servicios Mejorados y estas modalidades pueden variar con el tiempo. Podemos ofrecerte Cr&eacute;ditos Habbo que pueden utilizarse para obtener Servicios Mejorados. Los Cr&eacute;ditos Habbo se deducen de tu cuenta a medida que realizas compras. En ning&uacute;n caso los Cr&eacute;ditos Habbo son convertibles en euros.
4.5 Sin perjuicio de disposiciones contrarias dictadas por la ley o en relaci&oacute;n con ofertas de servicios particulares, ning&uacute;n pago o gasto ser&aacute; reembolsado.
4.6 En cuanto nos encargues Servicios y en particular Servicios Mejorados a trav&eacute;s del Sitio, y sin perjuicio de las disposiciones legales aplicables, no puedes, a partir de la puesta a disposici&oacute;n de estos servicios, poner fin al contrato existente entre t&uacute; y nosotros salvo respetando las disposiciones de las presentes Condiciones de uso o de las Condiciones Particulares que puedan acompa&ntilde;ar la oferta de ciertos Servicios.
4.7 Si eres menor de dieciocho (18) a&ntilde;os, debes obtener la autorizaci&oacute;n de la persona que paga la factura antes de comprometerte a pagar gastos.

5. Exclusi&oacute;n de garant&iacute;as
5.1 Falta de exactitud del Contenido. El conjunto del Contenido ofrecido por el Sitio (incluido el Contenido de los Usuarios) se te proporciona exclusivamente a t&iacute;tulo personal. Sulake France o las dem&aacute;s empresas del Grupo Sulake no pueden ser responsables del Contenido del Sitio, especialmente de las p&aacute;ginas de inicio, los foros de debate o las mensajer&iacute;as instant&aacute;neas. El Contenido (excluyendo el contenido de los usuarios) e informaci&oacute;n puesta a tu disposici&oacute;n en el Sitio es exacta cuando es publicada en l&iacute;nea en el Sitio por Sulake France. No obstante, no ofrecemos ninguna garant&iacute;a en cuanto a la exactitud en todo momento, el car&aacute;cter completo o actualizado de dicha informaci&oacute;n. No podemos ser responsables de las consecuencias de una dependencia de este contenido que te resulte perjudicial.
5.2 Falta de funcionamiento del Sitio. Te proporcionamos el Sitio tal cual. No garantizamos que el Sitio o los Contenidos est&eacute;n disponibles de manera permanente y sin errores. No ofrecemos ninguna garant&iacute;a relativa al funcionamiento del Sitio o su Contenido ni a las informaciones que contiene. En particular, no ofrecemos ninguna garant&iacute;a en cuanto a la calidad, exactitud, eficacia, exhaustividad y rendimiento del Sitio, ni en cuanto a la ausencia en el Sitio de cualquier error, virus u otro c&oacute;digo que pueda conducir a la contaminaci&oacute;n o destrucci&oacute;n de sistemas de informaci&oacute;n, as&iacute; como la falta de cualquier disfuncionamiento o interrupci&oacute;n del Servicio. En consecuencia, ni la responsabilidad de Sulake France ni la de las dem&aacute;s empresas del Grupo Sulake pueden ser comprometidas respecto a los elementos antes mencionados.

5.3 Seguridad: A excepci&oacute;n de las disposiciones expresas de nuestra CARTA DE PROTECCI&Oacute;N DE DATOS PERSONALES, Sulake France no ofrece ninguna garant&iacute;a en cuanto a la seguridad de las informaciones que puedas estar llamado a divulgar ni en cuanto a las actividades que puedas estar llamado a ejercer en el curso del uso del Sitio.
5.4 SIN PERJUICIO DE LAS DISPOSICIONES LEGALES, EXCLUIMOS TODA GARANT&Iacute;A EXPRESA O IMPL&Iacute;CITA EN CUANTO A TU USO DEL SITIO. NO OFRECEMOS NINGUNA GARANT&Iacute;A EN CUANTO A LOS CONTENIDOS PRESENTES EN EL SITIO O LOS CONTENIDOS PRESENTES EN OTROS SITIOS INTERNET A LOS QUE REMITEN ENLACES PRESENTES EN EL SITIO. Reconoces expresamente asumir el conjunto de los riesgos vinculados al uso del Sitio y de su Contenido, productos y servicios (incluidos en particular las p&aacute;ginas de inicio, foros de debate y mensajer&iacute;as instant&aacute;neas), de los Programas inform&aacute;ticos y otras actividades propuestas en el Sitio, y ser el &uacute;nico responsable de las consecuencias de dicho uso.
5.5 El uso del Sitio viene acompa&ntilde;ado de garant&iacute;as que, en virtud de la legislaci&oacute;n protectora de los consumidores, no pueden excluirse y seg&uacute;n las cuales, en particular, el Sitio deber&aacute; ser puesto a disposici&oacute;n con cuidado y ser conforme con el destino que se le atribuye.

6. Exclusi&oacute;n y limitaci&oacute;n de responsabilidad
6.1 En la medida permitida por la ley, no podremos ser responsables y excluimos expresamente toda responsabilidad por p&eacute;rdidas o da&ntilde;os que hayas sufrido a causa de a) los Contenidos presentes en el Sitio o en otros sitios Internet a los que remiten enlaces presentes en el sitio, en particular por cualquier error, omisi&oacute;n o inexactitud relativa a dichos Contenidos; b) bienes o servicios que te hubieran sido proporcionados por un tercero a trav&eacute;s del Sitio; c) cualquier Contenido publicado en el Sitio con tu nombre de usuario y contrase&ntilde;a; d) la supresi&oacute;n o el fallo en la conservaci&oacute;n o transmisi&oacute;n de cualquier Contenido en el Sitio; e) una vulneraci&oacute;n de tus bienes sufrida en el marco de tu uso del Sitio; f) un acceso no autorizado a tus datos de car&aacute;cter personal conservados en nuestras bases de datos; g) las vulnerabilidades y virus que un tercero pudiera haber transmitido a tu ordenador en el marco de tu uso del Sitio; o h) cualquier interrupci&oacute;n del funcionamiento del Sitio.
6.2 EXCLUIMOS EXPRESAMENTE TODA RESPONSABILIDAD A TU RESPECTO POR O EN RELACI&Oacute;N CON LA P&Eacute;RDIDA INDIRECTA O CONSECUENTE, EN PARTICULAR LA PRIVACI&Oacute;N DE DISFRUTE, EL LUCRO CESANTE, LA P&Eacute;RDIDA DE UNA OPORTUNIDAD, LA P&Eacute;RDIDA DE DATOS, LA P&Eacute;RDIDA DE PRODUCCI&Oacute;N, LA P&Eacute;RDIDA DE OPORTUNIDADES O EL CESE DE EXPLOTACI&Oacute;N SUFRIDO COMO CONSECUENCIA DE TU USO DEL SITIO.
6.3 SIN PERJUICIO DE LAS ESTIPULACIONES ANTERIORES, SI NUESTRA RESPONSABILIDAD FUERA COMPROMETIDA EN EL MARCO DE TU USO DEL SITIO, EL IMPORTE DE LA INDEMNIZACI&Oacute;N A LA QUE PUEDES PRETENDER SE LIMITA AL IMPORTE DE LAS SUMAS QUE HAS PAGADO DURANTE LOS TRES &Uacute;LTIMOS MESES INMEDIATAMENTE ANTERIORES AL HECHO GENERADOR DE LA ACCI&Oacute;N, EN SU CASO.
6.4 Reconoces que las exclusiones y limitaciones de responsabilidad previstas en los Art&iacute;culos 6.1, 6.2 y 6.3 se aplican cualquiera que sea la naturaleza del da&ntilde;o, p&eacute;rdida, coste, gastos o acci&oacute;n y cualquiera que sea el fundamento de dicha acci&oacute;n y la naturaleza de la pretendida responsabilidad buscada.

7. Indemnizaci&oacute;n
Aceptas indemnizarnos a nosotros y a nuestros derechohabientes por todas las p&eacute;rdidas, gastos, da&ntilde;os y costes, en la medida de lo razonable, responsabilidad, reclamaci&oacute;n y gastos incurridos (incluidos, sobre la base de una reparaci&oacute;n &iacute;ntegra, todos los gastos jur&iacute;dicos o incurridos para nuestra defensa o cualquier acuerdo amistoso) que puedan resultar a) del incumplimiento de las presentes Condiciones de uso, b) del uso del Sitio con tu nombre de usuario y contrase&ntilde;a o c) de una vulneraci&oacute;n por tu parte de los derechos de terceros. Las disposiciones de este p&aacute;rrafo est&aacute;n destinadas a proteger a Sulake France y a sus gerentes, responsables, empleados, agentes, accionistas, concedentes de licencia y proveedores. Cada una de estas personas o entidades podr&aacute;, en su propio nombre, hacer valer estas disposiciones directamente en tu contra.

8. Garant&iacute;a
Nos garantizas que: a) tienes la capacidad y los poderes requeridos para celebrar este Contrato y ejecutar las obligaciones que de &eacute;l resultan para ti; b) posees todos los derechos correspondientes a los Contenidos que publicas en el Sitio o que el propietario de dichos Contenidos te ha otorgado todos los derechos requeridos para publicarlos en el Sitio; c) los Contenidos que publicas en el Sitio son conformes con el art&iacute;culo 2 de las presentes (L&iacute;mites aplicables a los Contenidos); d) asumir&aacute;s el pago de cualquier honorario, remuneraci&oacute;n u otra suma debida a terceros (incluidas las sociedades de gesti&oacute;n colectiva de derechos de autor) por los Contenidos que publicas en el Sitio; y e) que tienes la capacidad y los poderes requeridos para realizar cualquier adquisici&oacute;n en el Sitio.

9. Enlaces hacia sitios Internet gestionados por terceros
9.1 Reconoces y aceptas que algunos enlaces del sitio remiten a recursos situados en servidores gestionados por terceros sobre los que no ejercemos ning&uacute;n control y cuyas actividades no est&aacute;n controladas por Sulake France. En consecuencia, excluimos toda responsabilidad relativa a la disponibilidad y el contenido de los recursos y sitios accesibles a trav&eacute;s de dichos servidores. Eres el &uacute;nico responsable de la evaluaci&oacute;n de los bienes y servicios ofrecidos por dichos terceros a trav&eacute;s del sitio. En este marco, no somos parte y no asumimos ninguna responsabilidad en el marco de la transacci&oacute;n que puedas celebrar con dichos terceros, ni tampoco del contenido de las informaciones que estos &uacute;ltimos puedan proporcionar en el marco de sus ofertas.
9.2 Al usar los enlaces hacia sitios de terceros que son accesibles en el sitio, puedes recibir &quot;cookies&quot; y tus datos personales pueden ser recopilados. Excluimos toda responsabilidad a este respecto en la medida en que no ejercemos ning&uacute;n control sobre dichos sitios y dichas acciones.
9.3 En cuanto a los anuncios publicitarios y cualquier otro elemento relativo a la publicidad que figuran en el sitio y remitidos por terceros, dichos terceros, en tanto que anunciantes, son los &uacute;nicos responsables de la conformidad de sus anuncios y elementos con la normativa aplicable, y excluimos toda responsabilidad a este respecto.

10. Normas generales de conducta y de almacenamiento
10.1 Nos reservamos el derecho de establecer normas de conducta y de imponer l&iacute;mites en cuanto al uso del servicio. Podemos, por ejemplo, fijar:
(a) un n&uacute;mero m&aacute;ximo de d&iacute;as durante los cuales los mensajes o cualquier otro contenido cargado al sitio ser&aacute;n conservados en el marco del servicio;
(b) un n&uacute;mero o volumen m&aacute;ximo de mensajes que pueden ser enviados o recibidos por una cuenta abierta en el servicio;
(c) una capacidad m&aacute;xima de memoria que ser&aacute; asignada por nuestros servidores para tu cuenta;
(d) un n&uacute;mero m&aacute;ximo de veces que puedes acceder al servicio, as&iacute; como una duraci&oacute;n m&aacute;xima de cada acceso durante un per&iacute;odo determinado.

11. Protecci&oacute;n de datos personales
La informaci&oacute;n personal que nos proporcionas es tratada en estricta conformidad con nuestra Carta de protecci&oacute;n de datos personales, que proporciona en particular detalles sobre tus derechos relativos a tus datos personales y que forma parte integrante de las presentes condiciones de uso. Los t&eacute;rminos &quot;datos personales&quot; est&aacute;n definidos en dicha Carta. Te invitamos a leerla atentamente antes de comunicarnos tus datos personales. Si no adhi&egrave;res a los t&eacute;rminos de dicha Carta, te rogamos que no nos comuniques tales datos de car&aacute;cter personal. Llamamos tu atenci&oacute;n sobre el hecho de que esta carta no se aplica a los sitios Internet gestionados por terceros.

12. Rescisi&oacute;n y suspensi&oacute;n
12.1 Puedes rescindir este Contrato en cualquier momento y por cualquier motivo (por ejemplo porque no hemos respetado los t&eacute;rminos de este Contrato) sin penalizaciones envi&aacute;ndonos un correo electr&oacute;nico. Si has pagado para acceder a funcionalidades del Sitio sujetas a per&iacute;odos m&iacute;nimos de suscripci&oacute;n en virtud de las Condiciones Particulares que les son aplicables, tendr&aacute;s acceso al Sitio hasta la expiraci&oacute;n del plazo, siempre que no ejerzamos nuestro propio derecho a rescisi&oacute;n de conformidad con el art&iacute;culo 12.2 de las presentes. En todo caso, no procederemos a ning&uacute;n reembolso de la totalidad o parte de las sumas que ya te hayamos facturado y este Contrato seguir&aacute; siendo plenamente aplicable hasta su t&eacute;rmino.
12.2 Podemos poner fin a este Contrato en cualquier momento, con o sin notificaci&oacute;n previa: a) si no respetas o si tenemos motivos razonables para creer que no has respetado los t&eacute;rminos de este Contrato, tras notificaci&oacute;n previa para que pongas fin a la vulneraci&oacute;n del Contrato; o b) si tu cuenta est&aacute; inactiva desde hace m&aacute;s de seis meses y no tienes acceso a funcionalidades de pago. Tambi&eacute;n podremos poner fin a este Contrato en cualquier momento y por cualquier motivo tras haberte informado previamente un mes antes mediante un correo electr&oacute;nico enviado a la direcci&oacute;n que nos hayas comunicado. En caso de rescisi&oacute;n en virtud del art&iacute;culo 12.2 a) no podr&aacute;s pretender el reembolso de las sumas que nos hayas abonado.
12.3 Podemos suspender el acceso a tu cuenta si no respetas o si tenemos motivos razonables para creer que no has respetado los t&eacute;rminos de este Contrato. En este caso, no podr&aacute;s pretender el reembolso de las sumas que nos hayas abonado.

13. Consecuencia de la rescisi&oacute;n
Si pones fin, si nosotros ponemos fin a este Contrato o si suspendemos el acceso a tu cuenta respectivamente en virtud de los art&iacute;culos 12.1, 12.2 o 12.3, podremos suprimir tu perfil (incluida la informaci&oacute;n proporcionada para el registro) y cualquier Contenido que hayas publicado en el Sitio. Por este motivo, te recomendamos conservar una copia de cualquier Contenido (en particular de los art&iacute;culos de blog, im&aacute;genes, archivos de v&iacute;deo y audio) que hayas publicado en el Sitio. Nos reservamos el derecho de conservar tu perfil y cualquier Contenido que hayas publicado en el Sitio, en nuestros servidores durante un per&iacute;odo razonable tras la rescisi&oacute;n de este Contrato.

14. Modificaci&oacute;n del sitio
14.1 Nos reservamos el derecho discrecional de modificar, suspender o poner fin a la explotaci&oacute;n del Sitio o de suprimir una funcionalidad en cualquier momento y por cualquier motivo.
14.2 La modificaci&oacute;n del Sitio en aplicaci&oacute;n del art&iacute;culo 14.1 podr&aacute; realizarse sin notificaci&oacute;n previa cuando tenga un impacto positivo o neutro para ti.
14.3 Si la modificaci&oacute;n del Sitio en aplicaci&oacute;n del art&iacute;culo 14.1 es susceptible de tener un impacto material negativo para ti, te dirigiremos, con suficiente antelaci&oacute;n, una notificaci&oacute;n de dicha modificaci&oacute;n por correo electr&oacute;nico a la direcci&oacute;n que nos hayas comunicado y podr&aacute;s ejercer tu derecho a rescindir este Contrato de conformidad con el art&iacute;culo 12.1 de las presentes.
Un ejemplo de modificaci&oacute;n del Sitio que podr&iacute;a tener un impacto material negativo para ti podr&iacute;a ser la supresi&oacute;n de una funcionalidad clave del Sitio puesta de relieve, sin ofrecer una funcionalidad alternativa comparable.
14.4 Si la modificaci&oacute;n del Sitio puesta en pr&aacute;ctica supone que cambies de programa inform&aacute;tico, equipo o conexi&oacute;n a Internet para continuar us&aacute;ndolo, los gastos correspondientes a dichos cambios correr&aacute;n a tu exclusiva cuenta.

15. Modificaci&oacute;n de las condiciones de uso
15.1 Nos reservamos el derecho discrecional de modificar el presente Contrato, incluido el aumento de los gastos de acceso a las funcionalidades del Sitio en cualquier momento. Tu uso del Sitio tras la puesta en pr&aacute;ctica de tales modificaciones se considerar&aacute; que implica la aceptaci&oacute;n de este Contrato modificado por tu parte.
15.2 La modificaci&oacute;n del Contrato en aplicaci&oacute;n del art&iacute;culo 15.1 podr&aacute; realizarse sin notificaci&oacute;n previa cuando tenga un impacto positivo o neutro para ti.
15.3 Si la modificaci&oacute;n del Contrato en aplicaci&oacute;n del art&iacute;culo 15.1 es susceptible de tener un impacto material negativo para ti, te informaremos de estas modificaciones, con suficiente antelaci&oacute;n, mediante un mensaje publicado en l&iacute;nea en la p&aacute;gina de inicio del presente Sitio, y podr&aacute;s ejercer tu derecho a rescindir este Contrato de conformidad con el art&iacute;culo 12.1 de las presentes.
15.4 Te invitamos a consultar regularmente la versi&oacute;n actualizada de este Contrato AQU&Iacute;.

16. Concursos y premios
Peri&oacute;dicamente, nosotros o nuestros socios organizaremos concursos, juegos, sorteos gratuitos y promociones en el Sitio. Estos estar&aacute;n sujetos a Condiciones Particulares que comunicaremos en el momento de dichos juegos concurso.

17. Seguridad en Internet
Si eres menor de dieciocho (18) a&ntilde;os y tienes la intenci&oacute;n de usar el Sitio, debes leer y respetar las normas de seguridad en Internet disponibles en el enlace http://www.mineurs.fr/index.htm.

18. Protecci&oacute;n de los derechos de autor
Si consideras que la presencia de un Contenido vulnera tus derechos de autor, te rogamos que te pongas en contacto con nosotros por correo electr&oacute;nico para comunic&aacute;rnoslo.

19. Disposiciones generales
19.1 Las presentes Condiciones de uso se rigen por la ley espa&ntilde;ola. Sin perjuicio de la aplicaci&oacute;n de las disposiciones de orden p&uacute;blico, todo litigio surgido con ocasi&oacute;n del uso del Sitio o de las Condiciones de uso ser&aacute; de la competencia exclusiva de los tribunales espa&ntilde;oles.
19.2 El hecho de que no ejerzamos, o tardemos en ejercer, cualquiera de los derechos que poseemos en virtud de las presentes Condiciones de uso o de la ley, no puede constituir ni puede interpretarse como una renuncia a dichos derechos. Si uno de los art&iacute;culos de las presentes Condiciones de uso es considerado caduco o nulo por cualquier jurisdicci&oacute;n competente, se considerar&aacute; no escrito pero no implicar&aacute; la nulidad ni la caducidad de los dem&aacute;s art&iacute;culos de las presentes Condiciones de uso.
19.3 La cesi&oacute;n de los derechos de los que dispones en virtud de las presentes est&aacute; sujeta a nuestro acuerdo previo, que puedes solicitar envi&aacute;ndonos un correo electr&oacute;nico.
19.4 Reconoces y aceptas que podemos, en cualquier momento, ceder y transferir a un tercero los derechos y responsabilidades que resultan de las presentes; dicho tercero podr&aacute; asumir desde entonces las responsabilidades y obligaciones estipuladas en las presentes y te dirigiremos una notificaci&oacute;n en tal hip&oacute;tesis.
19.5 Los t&iacute;tulos de los art&iacute;culos de las presentes Condiciones de uso tienen &uacute;nicamente valor indicativo.
19.6 Las presentes Condiciones de uso constituyen la totalidad del acuerdo entre t&uacute; y nosotros respecto a tu uso del Sitio.
19.7 Salvo disposici&oacute;n contraria, los importes de los precios se indican y son pagaderos en euros.
ANTES DE CUALQUIER USO DEL SITIO, RECONOCES HABER TOMADO CONOCIMIENTO Y ACEPTADO LAS PRESENTES CONDICIONES DE USO AS&Iacute; COMO NUESTRA CARTA DE PROTECCI&Oacute;N DE DATOS PERSONALES.

Esta es la copia de las condiciones de uso de Habbo.fr.
Te recordamos tambi&eacute;n que los Habbos retros son ilegales.";

// Privacy Policy
$locale['privacy_policy_title'] = "Informaci&oacute;n pr&aacute;ctica";
$locale['privacy_policy'] = "En <b>".$sitename."</b>, tu privacidad no se pone en riesgo en este juego. Todos tus datos personales est&aacute;n protegidos en nuestra base de datos, y tus contrase&ntilde;as est&aacute;n cifradas.
Adem&aacute;s, no usaremos ninguna de tus cuentas con fines personales.

Este CMS fue creado por Meth0d, y modificado en versi&oacute;n francesa por Bubble y Knock.
NakedCMS - NakedGroup

Socios: Ning&uacute;n socio";

?>
